name: database
description: Application local database

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drift: 2.17.0

dev_dependencies:
  flutter_lints: ^3.0.0
