name: database
description: Application local database

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  # Modules
  core:
    path: ../core

  flutter:
    sdk: flutter
  drift: 2.17.0
  sqlite3_flutter_libs: 0.5.0
  path_provider: 2.0.0
  path: 1.9.0

dev_dependencies:
  # Code generation
  build_runner: 2.4.9
  drift_dev: 2.17.0